"""Public API for the World Intelligence Federal Register source adapter."""

from .adapter import (
    ADAPTER_CAPABILITY,
    ADAPTER_CONTRACT,
    ADAPTER_IMPLEMENTATION_ID,
    ADAPTER_IMPLEMENTATION_VERSION,
    DEFAULT_DOCUMENT_PROFILE,
    DOCUMENT_NUMBER,
    DOCUMENT_TITLE,
    FEDERAL_REGISTER_DOCUMENT_URI,
    FEDERAL_REGISTER_LOCATOR,
    FEDERAL_REGISTER_SOURCE_TYPE,
    OFFICIAL_PDF_URI,
    FederalRegisterDocumentProfile,
    FederalRegisterRetrievalRequest,
    FederalRegisterRetrievalResult,
    FederalRegisterSourceAdapter,
    FederalRegisterSourceAdapterError,
    FederalRegisterTransport,
)

__all__ = [
    "ADAPTER_CAPABILITY",
    "ADAPTER_CONTRACT",
    "ADAPTER_IMPLEMENTATION_ID",
    "ADAPTER_IMPLEMENTATION_VERSION",
    "DEFAULT_DOCUMENT_PROFILE",
    "DOCUMENT_NUMBER",
    "DOCUMENT_TITLE",
    "FEDERAL_REGISTER_DOCUMENT_URI",
    "FEDERAL_REGISTER_LOCATOR",
    "FEDERAL_REGISTER_SOURCE_TYPE",
    "OFFICIAL_PDF_URI",
    "FederalRegisterDocumentProfile",
    "FederalRegisterRetrievalRequest",
    "FederalRegisterRetrievalResult",
    "FederalRegisterSourceAdapter",
    "FederalRegisterSourceAdapterError",
    "FederalRegisterTransport",
]
